### ISSUE TITLE
Python 2 only?

### ISSUE THREAD

**Issue by simonvh** [galaxyproject/cargo-port#123]
Given the following error:

```
$ galaxy-package-locator 
Traceback (most recent call last):
  File "/home/simon/anaconda3/bin/galaxy-package-locator", line 4, in <module>
    __import__('pkg_resources').run_script('cargo-port==1.0', 'galaxy-package-locator')
  File "/home/simon/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/simon/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/home/simon/anaconda3/lib/python3.5/site-packages/cargo_port-1.0-py3.5.egg/EGG-INFO/scripts/galaxy-package-locator", line 3, in <module>
    __requires__ = 'cargo-port==1.0'
ImportError: No module named 'urllib2'
```

I suspect it's currently Python 2 only? Might be good to specify that.

**Comment by bgruening** [comment]
You can also search the package here: https://depot.galaxyproject.org/software/
Currently, this tool is only python2, thats true.

**Comment by simonvh** [comment]
Yes, I found that, thanks! No complaints from my side, just a minor suggestion for the documentation.
